name: MSBuild CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Descargar el código
      uses: actions/checkout@v4

    - name: Configurar MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restaurar paquetes NuGet
      run: nuget restore ModernizacionEcuadorPractico/ModernizacionEcuadorPractico.sln

    - name: Compilar el proyecto
      run: msbuild ModernizacionEcuadorPractico/ModernizacionEcuadorPractico.sln /p:Configuration=Release
